### ISSUE TITLE
Undefined is not an object (evaluating 'PropTypes.oneOf')

### ISSUE THREAD

**Issue by rexlow** [lelandrichardson/react-native-pan-controller#9]
I am getting this error as soon as I install this module on my project.
Rebuild the project and the problem still persists.
Error occurs at 

> PanController.js:9

**Comment by arnavyagnik** [comment]
the file needs to be updated, the import statements changed in later versions. 

for the error you mentioned you can change require statements to:

```
import React, { PropTypes } from 'react'
import {
  View,
  Animated,
  PanResponder,
} from 'react-native'
```

P.S : you can also use require instead of import.
